//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniNFeTXT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniNFeTXT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAMM.
        /// </summary>
        internal static string AAMM {
            get {
                return ResourceManager.GetString("AAMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anoFab.
        /// </summary>
        internal static string anoFab {
            get {
                return ResourceManager.GetString("anoFab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anoMod.
        /// </summary>
        internal static string anoMod {
            get {
                return ResourceManager.GetString("anoMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cCor.
        /// </summary>
        internal static string cCor {
            get {
                return ResourceManager.GetString("cCor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cDV.
        /// </summary>
        internal static string cDV {
            get {
                return ResourceManager.GetString("cDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cEAN.
        /// </summary>
        internal static string cEAN {
            get {
                return ResourceManager.GetString("cEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cEANTrib.
        /// </summary>
        internal static string cEANTrib {
            get {
                return ResourceManager.GetString("cEANTrib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cEnq.
        /// </summary>
        internal static string cEnq {
            get {
                return ResourceManager.GetString("cEnq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        internal static string CEP {
            get {
                return ResourceManager.GetString("CEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cExportador.
        /// </summary>
        internal static string cExportador {
            get {
                return ResourceManager.GetString("cExportador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cFabricante.
        /// </summary>
        internal static string cFabricante {
            get {
                return ResourceManager.GetString("cFabricante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFOP.
        /// </summary>
        internal static string CFOP {
            get {
                return ResourceManager.GetString("CFOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chassi.
        /// </summary>
        internal static string chassi {
            get {
                return ResourceManager.GetString("chassi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clEnq.
        /// </summary>
        internal static string clEnq {
            get {
                return ResourceManager.GetString("clEnq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cListServ.
        /// </summary>
        internal static string cListServ {
            get {
                return ResourceManager.GetString("cListServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM3.
        /// </summary>
        internal static string CM3 {
            get {
                return ResourceManager.GetString("CM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMKG.
        /// </summary>
        internal static string CMKG {
            get {
                return ResourceManager.GetString("CMKG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cMod.
        /// </summary>
        internal static string cMod {
            get {
                return ResourceManager.GetString("cMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cMun.
        /// </summary>
        internal static string cMun {
            get {
                return ResourceManager.GetString("cMun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cMunFG.
        /// </summary>
        internal static string cMunFG {
            get {
                return ResourceManager.GetString("cMunFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNAE.
        /// </summary>
        internal static string CNAE {
            get {
                return ResourceManager.GetString("CNAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cNF.
        /// </summary>
        internal static string cNF {
            get {
                return ResourceManager.GetString("cNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ.
        /// </summary>
        internal static string CNPJ {
            get {
                return ResourceManager.GetString("CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJProd.
        /// </summary>
        internal static string CNPJProd {
            get {
                return ResourceManager.GetString("CNPJProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODIF.
        /// </summary>
        internal static string CODIF {
            get {
                return ResourceManager.GetString("CODIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to condVeic.
        /// </summary>
        internal static string condVeic {
            get {
                return ResourceManager.GetString("condVeic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cPais.
        /// </summary>
        internal static string cPais {
            get {
                return ResourceManager.GetString("cPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        internal static string CPF {
            get {
                return ResourceManager.GetString("CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cProd.
        /// </summary>
        internal static string cProd {
            get {
                return ResourceManager.GetString("cProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cProdANP.
        /// </summary>
        internal static string cProdANP {
            get {
                return ResourceManager.GetString("cProdANP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cSelo.
        /// </summary>
        internal static string cSelo {
            get {
                return ResourceManager.GetString("cSelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CST.
        /// </summary>
        internal static string CST {
            get {
                return ResourceManager.GetString("CST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cUF.
        /// </summary>
        internal static string cUF {
            get {
                return ResourceManager.GetString("cUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dDesemb.
        /// </summary>
        internal static string dDesemb {
            get {
                return ResourceManager.GetString("dDesemb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dDI.
        /// </summary>
        internal static string dDI {
            get {
                return ResourceManager.GetString("dDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dEmi.
        /// </summary>
        internal static string dEmi {
            get {
                return ResourceManager.GetString("dEmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descr.
        /// </summary>
        internal static string descr {
            get {
                return ResourceManager.GetString("descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dFab.
        /// </summary>
        internal static string dFab {
            get {
                return ResourceManager.GetString("dFab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dist.
        /// </summary>
        internal static string dist {
            get {
                return ResourceManager.GetString("dist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dPag.
        /// </summary>
        internal static string dPag {
            get {
                return ResourceManager.GetString("dPag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dSaiEnt.
        /// </summary>
        internal static string dSaiEnt {
            get {
                return ResourceManager.GetString("dSaiEnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dVal.
        /// </summary>
        internal static string dVal {
            get {
                return ResourceManager.GetString("dVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dVenc.
        /// </summary>
        internal static string dVenc {
            get {
                return ResourceManager.GetString("dVenc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to esp.
        /// </summary>
        internal static string esp {
            get {
                return ResourceManager.GetString("esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to espVeic.
        /// </summary>
        internal static string espVeic {
            get {
                return ResourceManager.GetString("espVeic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTIPI.
        /// </summary>
        internal static string EXTIPI {
            get {
                return ResourceManager.GetString("EXTIPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finNFe.
        /// </summary>
        internal static string finNFe {
            get {
                return ResourceManager.GetString("finNFe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fone.
        /// </summary>
        internal static string fone {
            get {
                return ResourceManager.GetString("fone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genero.
        /// </summary>
        internal static string genero {
            get {
                return ResourceManager.GetString("genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE.
        /// </summary>
        internal static string IE {
            get {
                return ResourceManager.GetString("IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IEST.
        /// </summary>
        internal static string IEST {
            get {
                return ResourceManager.GetString("IEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM.
        /// </summary>
        internal static string IM {
            get {
                return ResourceManager.GetString("IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indPag.
        /// </summary>
        internal static string indPag {
            get {
                return ResourceManager.GetString("indPag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indProc.
        /// </summary>
        internal static string indProc {
            get {
                return ResourceManager.GetString("indProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to infAdFisco.
        /// </summary>
        internal static string infAdFisco {
            get {
                return ResourceManager.GetString("infAdFisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to infAdProd.
        /// </summary>
        internal static string infAdProd {
            get {
                return ResourceManager.GetString("infAdProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to infCpl.
        /// </summary>
        internal static string infCpl {
            get {
                return ResourceManager.GetString("infCpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISUF.
        /// </summary>
        internal static string ISUF {
            get {
                return ResourceManager.GetString("ISUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marca.
        /// </summary>
        internal static string marca {
            get {
                return ResourceManager.GetString("marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matr.
        /// </summary>
        internal static string matr {
            get {
                return ResourceManager.GetString("matr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mod.
        /// </summary>
        internal static string mod {
            get {
                return ResourceManager.GetString("mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modBC.
        /// </summary>
        internal static string modBC {
            get {
                return ResourceManager.GetString("modBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modBCST.
        /// </summary>
        internal static string modBCST {
            get {
                return ResourceManager.GetString("modBCST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modFrete.
        /// </summary>
        internal static string modFrete {
            get {
                return ResourceManager.GetString("modFrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo da primeira linha do arquivo deve ser &apos;NOTAFISCAL&apos;.
        /// </summary>
        internal static string msg_001 {
            get {
                return ResourceManager.GetString("msg_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nAdicao.
        /// </summary>
        internal static string nAdicao {
            get {
                return ResourceManager.GetString("nAdicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to natOp.
        /// </summary>
        internal static string natOp {
            get {
                return ResourceManager.GetString("natOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nCano.
        /// </summary>
        internal static string nCano {
            get {
                return ResourceManager.GetString("nCano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCM.
        /// </summary>
        internal static string NCM {
            get {
                return ResourceManager.GetString("NCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nDAR.
        /// </summary>
        internal static string nDAR {
            get {
                return ResourceManager.GetString("nDAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nDI.
        /// </summary>
        internal static string nDI {
            get {
                return ResourceManager.GetString("nDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nDup.
        /// </summary>
        internal static string nDup {
            get {
                return ResourceManager.GetString("nDup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nFat.
        /// </summary>
        internal static string nFat {
            get {
                return ResourceManager.GetString("nFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFref.
        /// </summary>
        internal static string NFref {
            get {
                return ResourceManager.GetString("NFref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nLacre.
        /// </summary>
        internal static string nLacre {
            get {
                return ResourceManager.GetString("nLacre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nLote.
        /// </summary>
        internal static string nLote {
            get {
                return ResourceManager.GetString("nLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nMotor.
        /// </summary>
        internal static string nMotor {
            get {
                return ResourceManager.GetString("nMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNF.
        /// </summary>
        internal static string nNF {
            get {
                return ResourceManager.GetString("nNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nProc.
        /// </summary>
        internal static string nProc {
            get {
                return ResourceManager.GetString("nProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nro.
        /// </summary>
        internal static string nro {
            get {
                return ResourceManager.GetString("nro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nSeqAdic.
        /// </summary>
        internal static string nSeqAdic {
            get {
                return ResourceManager.GetString("nSeqAdic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nSerie.
        /// </summary>
        internal static string nSerie {
            get {
                return ResourceManager.GetString("nSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nVol.
        /// </summary>
        internal static string nVol {
            get {
                return ResourceManager.GetString("nVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orig.
        /// </summary>
        internal static string orig {
            get {
                return ResourceManager.GetString("orig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pCOFINS.
        /// </summary>
        internal static string pCOFINS {
            get {
                return ResourceManager.GetString("pCOFINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pesoB.
        /// </summary>
        internal static string pesoB {
            get {
                return ResourceManager.GetString("pesoB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pesoL.
        /// </summary>
        internal static string pesoL {
            get {
                return ResourceManager.GetString("pesoL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pICMS.
        /// </summary>
        internal static string pICMS {
            get {
                return ResourceManager.GetString("pICMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pICMSRet.
        /// </summary>
        internal static string pICMSRet {
            get {
                return ResourceManager.GetString("pICMSRet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pICMSST.
        /// </summary>
        internal static string pICMSST {
            get {
                return ResourceManager.GetString("pICMSST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pIPI.
        /// </summary>
        internal static string pIPI {
            get {
                return ResourceManager.GetString("pIPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PISOutr.
        /// </summary>
        internal static string PISOutr {
            get {
                return ResourceManager.GetString("PISOutr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to placa.
        /// </summary>
        internal static string placa {
            get {
                return ResourceManager.GetString("placa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pMVAST.
        /// </summary>
        internal static string pMVAST {
            get {
                return ResourceManager.GetString("pMVAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pot.
        /// </summary>
        internal static string pot {
            get {
                return ResourceManager.GetString("pot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pPIS.
        /// </summary>
        internal static string pPIS {
            get {
                return ResourceManager.GetString("pPIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pRedBC.
        /// </summary>
        internal static string pRedBC {
            get {
                return ResourceManager.GetString("pRedBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pRedBCST.
        /// </summary>
        internal static string pRedBCST {
            get {
                return ResourceManager.GetString("pRedBCST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to procEmi.
        /// </summary>
        internal static string procEmi {
            get {
                return ResourceManager.GetString("procEmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qBCProd.
        /// </summary>
        internal static string qBCProd {
            get {
                return ResourceManager.GetString("qBCProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qCom.
        /// </summary>
        internal static string qCom {
            get {
                return ResourceManager.GetString("qCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qLote.
        /// </summary>
        internal static string qLote {
            get {
                return ResourceManager.GetString("qLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qSelo.
        /// </summary>
        internal static string qSelo {
            get {
                return ResourceManager.GetString("qSelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qTemp.
        /// </summary>
        internal static string qTemp {
            get {
                return ResourceManager.GetString("qTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qTrib.
        /// </summary>
        internal static string qTrib {
            get {
                return ResourceManager.GetString("qTrib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qUnid.
        /// </summary>
        internal static string qUnid {
            get {
                return ResourceManager.GetString("qUnid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qVol.
        /// </summary>
        internal static string qVol {
            get {
                return ResourceManager.GetString("qVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refNFe.
        /// </summary>
        internal static string refNFe {
            get {
                return ResourceManager.GetString("refNFe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENAVAM.
        /// </summary>
        internal static string RENAVAM {
            get {
                return ResourceManager.GetString("RENAVAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repEmi.
        /// </summary>
        internal static string repEmi {
            get {
                return ResourceManager.GetString("repEmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNTC.
        /// </summary>
        internal static string RNTC {
            get {
                return ResourceManager.GetString("RNTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serie.
        /// </summary>
        internal static string serie {
            get {
                return ResourceManager.GetString("serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tpAmb.
        /// </summary>
        internal static string tpAmb {
            get {
                return ResourceManager.GetString("tpAmb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tpArma.
        /// </summary>
        internal static string tpArma {
            get {
                return ResourceManager.GetString("tpArma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tpComb.
        /// </summary>
        internal static string tpComb {
            get {
                return ResourceManager.GetString("tpComb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tpEmis.
        /// </summary>
        internal static string tpEmis {
            get {
                return ResourceManager.GetString("tpEmis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tpImp.
        /// </summary>
        internal static string tpImp {
            get {
                return ResourceManager.GetString("tpImp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tpNF.
        /// </summary>
        internal static string tpNF {
            get {
                return ResourceManager.GetString("tpNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tpOp.
        /// </summary>
        internal static string tpOp {
            get {
                return ResourceManager.GetString("tpOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tpPint.
        /// </summary>
        internal static string tpPint {
            get {
                return ResourceManager.GetString("tpPint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tpVeic.
        /// </summary>
        internal static string tpVeic {
            get {
                return ResourceManager.GetString("tpVeic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uCom.
        /// </summary>
        internal static string uCom {
            get {
                return ResourceManager.GetString("uCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        internal static string UF {
            get {
                return ResourceManager.GetString("UF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UFcons.
        /// </summary>
        internal static string UFcons {
            get {
                return ResourceManager.GetString("UFcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UFDesemb.
        /// </summary>
        internal static string UFDesemb {
            get {
                return ResourceManager.GetString("UFDesemb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UFEmbarq.
        /// </summary>
        internal static string UFEmbarq {
            get {
                return ResourceManager.GetString("UFEmbarq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uTrib.
        /// </summary>
        internal static string uTrib {
            get {
                return ResourceManager.GetString("uTrib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vAliq.
        /// </summary>
        internal static string vAliq {
            get {
                return ResourceManager.GetString("vAliq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vAliqProd.
        /// </summary>
        internal static string vAliqProd {
            get {
                return ResourceManager.GetString("vAliqProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vBC.
        /// </summary>
        internal static string vBC {
            get {
                return ResourceManager.GetString("vBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vBCICMS.
        /// </summary>
        internal static string vBCICMS {
            get {
                return ResourceManager.GetString("vBCICMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vBCICMSST.
        /// </summary>
        internal static string vBCICMSST {
            get {
                return ResourceManager.GetString("vBCICMSST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vBCICMSSTCons.
        /// </summary>
        internal static string vBCICMSSTCons {
            get {
                return ResourceManager.GetString("vBCICMSSTCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vBCICMSSTDest.
        /// </summary>
        internal static string vBCICMSSTDest {
            get {
                return ResourceManager.GetString("vBCICMSSTDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vBCIRRF.
        /// </summary>
        internal static string vBCIRRF {
            get {
                return ResourceManager.GetString("vBCIRRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vBCRet.
        /// </summary>
        internal static string vBCRet {
            get {
                return ResourceManager.GetString("vBCRet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vBCRetPrev.
        /// </summary>
        internal static string vBCRetPrev {
            get {
                return ResourceManager.GetString("vBCRetPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vBCST.
        /// </summary>
        internal static string vBCST {
            get {
                return ResourceManager.GetString("vBCST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vCIDE.
        /// </summary>
        internal static string vCIDE {
            get {
                return ResourceManager.GetString("vCIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vCOFINS.
        /// </summary>
        internal static string vCOFINS {
            get {
                return ResourceManager.GetString("vCOFINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vDAR.
        /// </summary>
        internal static string vDAR {
            get {
                return ResourceManager.GetString("vDAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vDesc.
        /// </summary>
        internal static string vDesc {
            get {
                return ResourceManager.GetString("vDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vDescDI.
        /// </summary>
        internal static string vDescDI {
            get {
                return ResourceManager.GetString("vDescDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vDespAdu.
        /// </summary>
        internal static string vDespAdu {
            get {
                return ResourceManager.GetString("vDespAdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vDup.
        /// </summary>
        internal static string vDup {
            get {
                return ResourceManager.GetString("vDup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verProc.
        /// </summary>
        internal static string verProc {
            get {
                return ResourceManager.GetString("verProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vFrete.
        /// </summary>
        internal static string vFrete {
            get {
                return ResourceManager.GetString("vFrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vICMS.
        /// </summary>
        internal static string vICMS {
            get {
                return ResourceManager.GetString("vICMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vICMSRet.
        /// </summary>
        internal static string vICMSRet {
            get {
                return ResourceManager.GetString("vICMSRet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vICMSST.
        /// </summary>
        internal static string vICMSST {
            get {
                return ResourceManager.GetString("vICMSST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vICMSSTCons.
        /// </summary>
        internal static string vICMSSTCons {
            get {
                return ResourceManager.GetString("vICMSSTCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vICMSSTDest.
        /// </summary>
        internal static string vICMSSTDest {
            get {
                return ResourceManager.GetString("vICMSSTDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vII.
        /// </summary>
        internal static string vII {
            get {
                return ResourceManager.GetString("vII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN.
        /// </summary>
        internal static string VIN {
            get {
                return ResourceManager.GetString("VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vIOF.
        /// </summary>
        internal static string vIOF {
            get {
                return ResourceManager.GetString("vIOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vIPI.
        /// </summary>
        internal static string vIPI {
            get {
                return ResourceManager.GetString("vIPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vIRRF.
        /// </summary>
        internal static string vIRRF {
            get {
                return ResourceManager.GetString("vIRRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vISS.
        /// </summary>
        internal static string vISS {
            get {
                return ResourceManager.GetString("vISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vISSQN.
        /// </summary>
        internal static string vISSQN {
            get {
                return ResourceManager.GetString("vISSQN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vLiq.
        /// </summary>
        internal static string vLiq {
            get {
                return ResourceManager.GetString("vLiq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vNF.
        /// </summary>
        internal static string vNF {
            get {
                return ResourceManager.GetString("vNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vOrig.
        /// </summary>
        internal static string vOrig {
            get {
                return ResourceManager.GetString("vOrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vOutro.
        /// </summary>
        internal static string vOutro {
            get {
                return ResourceManager.GetString("vOutro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vPIS.
        /// </summary>
        internal static string vPIS {
            get {
                return ResourceManager.GetString("vPIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vPMC.
        /// </summary>
        internal static string vPMC {
            get {
                return ResourceManager.GetString("vPMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vProd.
        /// </summary>
        internal static string vProd {
            get {
                return ResourceManager.GetString("vProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vRetCOFINS.
        /// </summary>
        internal static string vRetCOFINS {
            get {
                return ResourceManager.GetString("vRetCOFINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vRetCSLL.
        /// </summary>
        internal static string vRetCSLL {
            get {
                return ResourceManager.GetString("vRetCSLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vRetPIS.
        /// </summary>
        internal static string vRetPIS {
            get {
                return ResourceManager.GetString("vRetPIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vRetPrev.
        /// </summary>
        internal static string vRetPrev {
            get {
                return ResourceManager.GetString("vRetPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vSeg.
        /// </summary>
        internal static string vSeg {
            get {
                return ResourceManager.GetString("vSeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vServ.
        /// </summary>
        internal static string vServ {
            get {
                return ResourceManager.GetString("vServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vST.
        /// </summary>
        internal static string vST {
            get {
                return ResourceManager.GetString("vST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vUnCom.
        /// </summary>
        internal static string vUnCom {
            get {
                return ResourceManager.GetString("vUnCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vUnid.
        /// </summary>
        internal static string vUnid {
            get {
                return ResourceManager.GetString("vUnid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vUnTrib.
        /// </summary>
        internal static string vUnTrib {
            get {
                return ResourceManager.GetString("vUnTrib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xAgente.
        /// </summary>
        internal static string xAgente {
            get {
                return ResourceManager.GetString("xAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xBairro.
        /// </summary>
        internal static string xBairro {
            get {
                return ResourceManager.GetString("xBairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xCampo.
        /// </summary>
        internal static string xCampo {
            get {
                return ResourceManager.GetString("xCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xCont.
        /// </summary>
        internal static string xCont {
            get {
                return ResourceManager.GetString("xCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xCor.
        /// </summary>
        internal static string xCor {
            get {
                return ResourceManager.GetString("xCor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xCpl.
        /// </summary>
        internal static string xCpl {
            get {
                return ResourceManager.GetString("xCpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xEnder.
        /// </summary>
        internal static string xEnder {
            get {
                return ResourceManager.GetString("xEnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xFant.
        /// </summary>
        internal static string xFant {
            get {
                return ResourceManager.GetString("xFant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xLgr.
        /// </summary>
        internal static string xLgr {
            get {
                return ResourceManager.GetString("xLgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xLocDesemb.
        /// </summary>
        internal static string xLocDesemb {
            get {
                return ResourceManager.GetString("xLocDesemb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xLocEmbarq.
        /// </summary>
        internal static string xLocEmbarq {
            get {
                return ResourceManager.GetString("xLocEmbarq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xMun.
        /// </summary>
        internal static string xMun {
            get {
                return ResourceManager.GetString("xMun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xNEmp.
        /// </summary>
        internal static string xNEmp {
            get {
                return ResourceManager.GetString("xNEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xNome.
        /// </summary>
        internal static string xNome {
            get {
                return ResourceManager.GetString("xNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xOrgao.
        /// </summary>
        internal static string xOrgao {
            get {
                return ResourceManager.GetString("xOrgao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xPais.
        /// </summary>
        internal static string xPais {
            get {
                return ResourceManager.GetString("xPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xPed.
        /// </summary>
        internal static string xPed {
            get {
                return ResourceManager.GetString("xPed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xProd.
        /// </summary>
        internal static string xProd {
            get {
                return ResourceManager.GetString("xProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xTexto.
        /// </summary>
        internal static string xTexto {
            get {
                return ResourceManager.GetString("xTexto", resourceCulture);
            }
        }
    }
}
