//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContratosClient.GEDServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GedVersaoDocumentoDTO", Namespace="http://schemas.datacontract.org/2004/07/GEDService.Model")]
    [System.SerializableAttribute()]
    public partial class GedVersaoDocumentoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaminhoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashArquivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdColaboradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VersaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Acao {
            get {
                return this.AcaoField;
            }
            set {
                if ((object.ReferenceEquals(this.AcaoField, value) != true)) {
                    this.AcaoField = value;
                    this.RaisePropertyChanged("Acao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caminho {
            get {
                return this.CaminhoField;
            }
            set {
                if ((object.ReferenceEquals(this.CaminhoField, value) != true)) {
                    this.CaminhoField = value;
                    this.RaisePropertyChanged("Caminho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataHora {
            get {
                return this.DataHoraField;
            }
            set {
                if ((this.DataHoraField.Equals(value) != true)) {
                    this.DataHoraField = value;
                    this.RaisePropertyChanged("DataHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashArquivo {
            get {
                return this.HashArquivoField;
            }
            set {
                if ((object.ReferenceEquals(this.HashArquivoField, value) != true)) {
                    this.HashArquivoField = value;
                    this.RaisePropertyChanged("HashArquivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdColaborador {
            get {
                return this.IdColaboradorField;
            }
            set {
                if ((this.IdColaboradorField.Equals(value) != true)) {
                    this.IdColaboradorField = value;
                    this.RaisePropertyChanged("IdColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDocumento {
            get {
                return this.IdDocumentoField;
            }
            set {
                if ((this.IdDocumentoField.Equals(value) != true)) {
                    this.IdDocumentoField = value;
                    this.RaisePropertyChanged("IdDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Versao {
            get {
                return this.VersaoField;
            }
            set {
                if ((this.VersaoField.Equals(value) != true)) {
                    this.VersaoField = value;
                    this.RaisePropertyChanged("Versao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GEDServiceReference.IGEDService")]
    public interface IGEDService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/deleteGedTipoDocumento", ReplyAction="http://tempuri.org/IGEDService/deleteGedTipoDocumentoResponse")]
        int deleteGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/salvarAtualizarGedTipoDocumento", ReplyAction="http://tempuri.org/IGEDService/salvarAtualizarGedTipoDocumentoResponse")]
        GEDClient.GEDServiceReference.GedTipoDocumentoDTO salvarAtualizarGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectGedTipoDocumento", ReplyAction="http://tempuri.org/IGEDService/selectGedTipoDocumentoResponse")]
        System.Collections.Generic.List<GEDClient.GEDServiceReference.GedTipoDocumentoDTO> selectGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectGedTipoDocumentoPagina", ReplyAction="http://tempuri.org/IGEDService/selectGedTipoDocumentoPaginaResponse")]
        System.Collections.Generic.List<GEDClient.GEDServiceReference.GedTipoDocumentoDTO> selectGedTipoDocumentoPagina(int primeiroResultado, int quantidadeResultados, GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/saveDocumento", ReplyAction="http://tempuri.org/IGEDService/saveDocumentoResponse")]
        GEDClient.GEDServiceReference.GedDocumentoDTO saveDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/updateDocumento", ReplyAction="http://tempuri.org/IGEDService/updateDocumentoResponse")]
        GEDClient.GEDServiceReference.GedDocumentoDTO updateDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/deleteDocumento", ReplyAction="http://tempuri.org/IGEDService/deleteDocumentoResponse")]
        int deleteDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectDocumento", ReplyAction="http://tempuri.org/IGEDService/selectDocumentoResponse")]
        System.Collections.Generic.List<GEDClient.GEDServiceReference.GedDocumentoDTO> selectDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectDocumentoId", ReplyAction="http://tempuri.org/IGEDService/selectDocumentoIdResponse")]
        GEDClient.GEDServiceReference.GedDocumentoDTO selectDocumentoId(GEDClient.GEDServiceReference.GedDocumentoDTO documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/deleteGedVersaoDocumento", ReplyAction="http://tempuri.org/IGEDService/deleteGedVersaoDocumentoResponse")]
        int deleteGedVersaoDocumento(ContratosClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/salvarAtualizarGedVersaoDocumento", ReplyAction="http://tempuri.org/IGEDService/salvarAtualizarGedVersaoDocumentoResponse")]
        ContratosClient.GEDServiceReference.GedVersaoDocumentoDTO salvarAtualizarGedVersaoDocumento(ContratosClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectGedVersaoDocumento", ReplyAction="http://tempuri.org/IGEDService/selectGedVersaoDocumentoResponse")]
        System.Collections.Generic.List<ContratosClient.GEDServiceReference.GedVersaoDocumentoDTO> selectGedVersaoDocumento(ContratosClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectGedVersaoDocumentoPagina", ReplyAction="http://tempuri.org/IGEDService/selectGedVersaoDocumentoPaginaResponse")]
        System.Collections.Generic.List<ContratosClient.GEDServiceReference.GedVersaoDocumentoDTO> selectGedVersaoDocumentoPagina(int primeiroResultado, int quantidadeResultados, ContratosClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectUsuario", ReplyAction="http://tempuri.org/IGEDService/selectUsuarioResponse")]
        GEDClient.GEDServiceReference.UsuarioDTO selectUsuario(string login, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectControleAcesso", ReplyAction="http://tempuri.org/IGEDService/selectControleAcessoResponse")]
        System.Collections.Generic.List<GEDClient.GEDServiceReference.ViewControleAcessoDTO> selectControleAcesso(GEDClient.GEDServiceReference.ViewControleAcessoDTO viewControleAcesso);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGEDServiceChannel : ContratosClient.GEDServiceReference.IGEDService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GEDServiceClient : System.ServiceModel.ClientBase<ContratosClient.GEDServiceReference.IGEDService>, ContratosClient.GEDServiceReference.IGEDService {
        
        public GEDServiceClient() {
        }
        
        public GEDServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GEDServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GEDServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GEDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int deleteGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento) {
            return base.Channel.deleteGedTipoDocumento(gedTipoDocumento);
        }
        
        public GEDClient.GEDServiceReference.GedTipoDocumentoDTO salvarAtualizarGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento) {
            return base.Channel.salvarAtualizarGedTipoDocumento(gedTipoDocumento);
        }
        
        public System.Collections.Generic.List<GEDClient.GEDServiceReference.GedTipoDocumentoDTO> selectGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento) {
            return base.Channel.selectGedTipoDocumento(gedTipoDocumento);
        }
        
        public System.Collections.Generic.List<GEDClient.GEDServiceReference.GedTipoDocumentoDTO> selectGedTipoDocumentoPagina(int primeiroResultado, int quantidadeResultados, GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento) {
            return base.Channel.selectGedTipoDocumentoPagina(primeiroResultado, quantidadeResultados, gedTipoDocumento);
        }
        
        public GEDClient.GEDServiceReference.GedDocumentoDTO saveDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento) {
            return base.Channel.saveDocumento(documento);
        }
        
        public GEDClient.GEDServiceReference.GedDocumentoDTO updateDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento) {
            return base.Channel.updateDocumento(documento);
        }
        
        public int deleteDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento) {
            return base.Channel.deleteDocumento(documento);
        }
        
        public System.Collections.Generic.List<GEDClient.GEDServiceReference.GedDocumentoDTO> selectDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento) {
            return base.Channel.selectDocumento(documento);
        }
        
        public GEDClient.GEDServiceReference.GedDocumentoDTO selectDocumentoId(GEDClient.GEDServiceReference.GedDocumentoDTO documento) {
            return base.Channel.selectDocumentoId(documento);
        }
        
        public int deleteGedVersaoDocumento(ContratosClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento) {
            return base.Channel.deleteGedVersaoDocumento(gedVersaoDocumento);
        }
        
        public ContratosClient.GEDServiceReference.GedVersaoDocumentoDTO salvarAtualizarGedVersaoDocumento(ContratosClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento) {
            return base.Channel.salvarAtualizarGedVersaoDocumento(gedVersaoDocumento);
        }
        
        public System.Collections.Generic.List<ContratosClient.GEDServiceReference.GedVersaoDocumentoDTO> selectGedVersaoDocumento(ContratosClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento) {
            return base.Channel.selectGedVersaoDocumento(gedVersaoDocumento);
        }
        
        public System.Collections.Generic.List<ContratosClient.GEDServiceReference.GedVersaoDocumentoDTO> selectGedVersaoDocumentoPagina(int primeiroResultado, int quantidadeResultados, ContratosClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento) {
            return base.Channel.selectGedVersaoDocumentoPagina(primeiroResultado, quantidadeResultados, gedVersaoDocumento);
        }
        
        public GEDClient.GEDServiceReference.UsuarioDTO selectUsuario(string login, string senha) {
            return base.Channel.selectUsuario(login, senha);
        }
        
        public System.Collections.Generic.List<GEDClient.GEDServiceReference.ViewControleAcessoDTO> selectControleAcesso(GEDClient.GEDServiceReference.ViewControleAcessoDTO viewControleAcesso) {
            return base.Channel.selectControleAcesso(viewControleAcesso);
        }
    }
}
